### ISSUE TITLE
Access descriptor from class object deduced to wrong type

### ISSUE THREAD

**Issue by yaxum62** [microsoft/pyright#1043]
**Describe the bug**

Pyright deducted  to wrong type when access descriptor directly from class object.
    
    class A:
        @property
        def value(self):
            return 42

    print(A.value.fget)
                  ~~~~ Cannot access member "fget" for type "Literal[42]"
    
**Expected behavior**
For example above, `A.value` should deduct to type `property`

**VS Code extension or command-line**
vscode extension v1.1.72

**Comment by erictraut** [comment]
Thanks for the bug report. This will be fixed in the next release of Pyright.

**Comment by erictraut** [comment]
This is addressed in Pyright 1.1.73, which I just published.

**Comment by yaxum62** [comment]
Thanks for the fix!

I should mention in the bug description that this bug applies to all descriptor objects with `__get__` method, not only for built in `property`. v1.1.73 seems fixed `property` but other descriptor type still got wrong deduction. I still see following error:

    class MyProperty:
        def __get__(self, obj, typ=None):
            return 42

    class A:
        value = MyProperty()
    
    print(A.value.__get__)
                  ~~~~~~~ Cannot access member "__get__" for type "Literal[42]"

In example above `A.value` should deducted to type `MyProperty`

**Comment by erictraut** [comment]
I think it's correct. If you run the code above, you will see the following exception:
```
AttributeError: 'int' object has no attribute '__get__'
```

The reason it works this way is that the `__get__` method in property is implemented like this:
```python
    def __get__(self, obj, typ=None):
        if obj is None:
            return self
        return self.fget(obj)
```

The `__get__` method in your custom property is not doing the same.

If you define your custom property to act more like the built-in `property` class, you will see that Pyright treats it the same:

```python
from typing import Any, overload

class MyProperty:
    @overload
    def __get__(self, obj: None, type=None) -> "MyProperty":
        ...
    @overload
    def __get__(self, obj: object, type=None) -> Any:
        ...
    def __get__(self, obj, typ=None):
        if obj is None:
            return self
        return 42

class A:
    value = MyProperty()

print(A.value.__get__)
```

**Comment by yaxum62** [comment]
Ah, I missed the case that obj could be None, thanks for the explaination!
