### ISSUE TITLE
Enum nonmembers not supported

### ISSUE THREAD

**Issue by Gouvernathor** [microsoft/pyright#7346]
## Environment data

-   Language Server version: 2024.2.2
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): cpython 3.12

## Code Snippet

```python
class Relationship(enum.Flag):
    # technical
    NONE = 0
    SELF = 1

    # direct
    PARENT = enum.auto()
    CHILD = enum.auto()
    SPOUSE = enum.auto()

    # testing methods {Relationship : (FamilyMember, FamilyMember) -> bool}
    # the order matters : the first matching relation will be preferred between two persons
    # all relationships should be there, except for None
    _testers: ClassVar[dict[Relationship, Callable[[FamilyMember, FamilyMember], bool]]] = enum.nonmember({})

def _relationship_tester(relationship: Relationship, /):
    def decorator(func):
        Relationship._testers[relationship] = func
        return func
    return decorator
```

## Repro Steps

The `enum.nonmember({})` is underlined and shows the error `Expression of type "nonmember[dict[Any, Any]]" cannot be assigned to declared type "Literal[Relationship._testers]"
"nonmember[dict[Any, Any]]" cannot be assigned to type "Literal[Relationship._testers]"Pylance(reportAssignmentType)
(module) enum`.
The `Relationship._testers` is underlined and shows the error `"__setitem__" method not defined on type "Literal[Relationship._testers]"Pylance(reportIndexIssue)
(variable) _testers: Literal[Relationship._testers]`. Writing `Relationship._testers.value` in its place looks fine to Pylance, but doesn't actually work.

It appears the module is disregarding both the nonmember decorator and the ClassVar type indication, and treats the object as a member of the enum.

**Comment by Gouvernathor** [comment]
Can confirm the main alert goes away. I still have this though.
![image](https://github.com/microsoft/pyright/assets/44340603/7a35345f-b74f-4a48-b4b1-449cf2629bcf)
It seems related to what you said last, but I'm not sure.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.352, which I just published.

**Comment by rchiodo** [comment]
Pylance version 2024.3.1 is only Pyright 1.1.351. 

Logs show this:
```
2024-03-14 10:35:57.064 [info] [Info  - 10:35:57 AM] (4984) Pylance language server 2024.3.1 (pyright version 1.1.351, commit 87171fbf) starting
```

If you upgrade to Pylance prerelease, it has the latest Pyright in it:

```
2024-03-14 10:33:16.034 [info] [Info  - 10:33:16 AM] (9724) Pylance language server 2024.3.100 (pyright version 1.1.354, commit 6c4b3291) starting
```

**Comment by Gouvernathor** [comment]
Can confirm that in the last Pylance prerelease, v2024.3.100, it is still flagged as an error.

**Comment by Gouvernathor** [comment]
This still fails in today's prerelease, v2024.3.101

**Comment by Gouvernathor** [comment]
This still fails in the current prerelease, v2024.3.102
@erictraut @rchiodo

**Comment by erictraut** [comment]
The original bug was addressed. If you think that a different issue exists, please file a new bug and include a self-contained, minimal code sample that demonstrates the problem.

**Comment by Gouvernathor** [comment]
#7595
