### ISSUE TITLE
Failed to parse pyproject.toml

### ISSUE THREAD

**Issue by CandiedCode** [microsoft/pyright#9412]
Upgrading from pyright 1.1.386 to 1.1.387 causes pyright to fail due to parsing issues with our pyproject.toml

```python
Pyproject file parse attempt 1 error: {"name":"SyntaxParseError","errors":[{"offset":9943,"line":409,"column":18,"length":16,"message":"unexpected character: ->\"<- at offset: 9943, skipped 16 characters."},{"offset":9960,"line":409,"column":35,"length":2,"message":"unexpected character: ->\ud83d<- at offset: 9960, skipped 2 characters."},{"offset":9972,"line":409,"column":47,"length":4,"message":"unexpected character: ->\\<- at offset: 9972, skipped 4 characters."},{"offset":9977,"line":409,"column":52,"length":4,"message":"unexpected character: ->s<- at offset: 9977, skipped 4 characters."},{"offset":9982,"line":409,"column":57,"length":2,"message":"unexpected character: ->c<- at offset: 9982, skipped 2 characters."},{"offset":9985,"line":409,"column":60,"length":1,"message":"unexpected character: ->\"<- at offset: 9985, skipped 1 characters."}]}
Pyproject file parse attempt 2 error: {"name":"SyntaxParseError","errors":[{"offset":9943,"line":409,"column":18,"length":16,"message":"unexpected character: ->\"<- at offset: 9943, skipped 16 characters."},{"offset":9960,"line":409,"column":35,"length":2,"message":"unexpected character: ->\ud83d<- at offset: 9960, skipped 2 characters."},{"offset":9972,"line":409,"column":47,"length":4,"message":"unexpected character: ->\\<- at offset: 9972, skipped 4 characters."},{"offset":9977,"line":409,"column":52,"length":4,"message":"unexpected character: ->s<- at offset: 9977, skipped 4 characters."},{"offset":9982,"line":409,"column":57,"length":2,"message":"unexpected character: ->c<- at offset: 9982, skipped 2 characters."},{"offset":9985,"line":409,"column":60,"length":1,"message":"unexpected character: ->\"<- at offset: 9985, skipped 1 characters."}]}
Pyproject file parse attempt 3 error: {"name":"SyntaxParseError","errors":[{"offset":9943,"line":409,"column":18,"length":16,"message":"unexpected character: ->\"<- at offset: 9943, skipped 16 characters."},{"offset":9960,"line":409,"column":35,"length":2,"message":"unexpected character: ->\ud83d<- at offset: 9960, skipped 2 characters."},{"offset":9972,"line":409,"column":47,"length":4,"message":"unexpected character: ->\\<- at offset: 9972, skipped 4 characters."},{"offset":9977,"line":409,"column":52,"length":4,"message":"unexpected character: ->s<- at offset: 9977, skipped 4 characters."},{"offset":9982,"line":409,"column":57,"length":2,"message":"unexpected character: ->c<- at offset: 9982, skipped 2 characters."},{"offset":9985,"line":409,"column":60,"length":1,"message":"unexpected character: ->\"<- at offset: 9985, skipped 1 characters."}]}
Pyproject file parse attempt 4 error: {"name":"SyntaxParseError","errors":[{"offset":9943,"line":409,"column":18,"length":16,"message":"unexpected character: ->\"<- at offset: 9943, skipped 16 characters."},{"offset":9960,"line":409,"column":35,"length":2,"message":"unexpected character: ->\ud83d<- at offset: 9960, skipped 2 characters."},{"offset":9972,"line":409,"column":47,"length":4,"message":"unexpected character: ->\\<- at offset: 9972, skipped 4 characters."},{"offset":9977,"line":409,"column":52,"length":4,"message":"unexpected character: ->s<- at offset: 9977, skipped 4 characters."},{"offset":9982,"line":409,"column":57,"length":2,"message":"unexpected character: ->c<- at offset: 9982, skipped 2 characters."},{"offset":9985,"line":409,"column":60,"length":1,"message":"unexpected character: ->\"<- at offset: 9985, skipped 1 characters."}]}
Pyproject file parse attempt 5 error: {"name":"SyntaxParseError","errors":[{"offset":9943,"line":409,"column":18,"length":16,"message":"unexpected character: ->\"<- at offset: 9943, skipped 16 characters."},{"offset":9960,"line":409,"column":35,"length":2,"message":"unexpected character: ->\ud83d<- at offset: 9960, skipped 2 characters."},{"offset":9972,"line":409,"column":47,"length":4,"message":"unexpected character: ->\\<- at offset: 9972, skipped 4 characters."},{"offset":9977,"line":409,"column":52,"length":4,"message":"unexpected character: ->s<- at offset: 9977, skipped 4 characters."},{"offset":9982,"line":409,"column":57,"length":2,"message":"unexpected character: ->c<- at offset: 9982, skipped 2 characters."},{"offset":9985,"line":409,"column":60,"length":1,"message":"unexpected character: ->\"<- at offset: 9985, skipped 1 characters."}]}
Pyproject file parse attempt 6 error: {"name":"SyntaxParseError","errors":[{"offset":9943,"line":409,"column":18,"length":16,"message":"unexpected character: ->\"<- at offset: 9943, skipped 16 characters."},{"offset":9960,"line":409,"column":35,"length":2,"message":"unexpected character: ->\ud83d<- at offset: 9960, skipped 2 characters."},{"offset":9972,"line":409,"column":47,"length":4,"message":"unexpected character: ->\\<- at offset: 9972, skipped 4 characters."},{"offset":9977,"line":409,"column":52,"length":4,"message":"unexpected character: ->s<- at offset: 9977, skipped 4 characters."},{"offset":9982,"line":409,"column":57,"length":2,"message":"unexpected character: ->c<- at offset: 9982, skipped 2 characters."},{"offset":9985,"line":409,"column":60,"length":1,"message":"unexpected character: ->\"<- at offset: 9985, skipped 1 characters."}]}
Config file "/Users/candiedcode/Code/api/pyproject.toml" could not be parsed. Verify that format is correct.
0 errors, 0 warnings, 0 informations 
```

It's failing due to our commit_message.
```toml
[tool.semantic_release]
build_command = "python -m pip install build && python -m build --wheel"
commit_message = "chore(release): 🔖 {version}\n\n[skip ci]"
major_on_zero = false
version_variables = [
    "llm_api/__init__.py:__version__",
]
```

**Comment by LeeeeT** [comment]
This is due to the recent switch to a different TOML parsing library (which presumably has a bug). Here's the upstream issue: https://github.com/sunnyadn/js-toml/issues/2.

**Comment by erictraut** [comment]
This is addressed in pyright 1.1.389

**Comment by ivan-klass** [comment]
Still got this issue on the latest version also:
```
Pyproject file parse attempt 1 error: {}
Pyproject file parse attempt 2 error: {}
Pyproject file parse attempt 3 error: {}
Pyproject file parse attempt 4 error: {}
Pyproject file parse attempt 5 error: {}
Pyproject file parse attempt 6 error: {}
Config file "/path/to/my/pyproject.toml" could not be parsed. Verify that format is correct.
```

**Comment by erictraut** [comment]
@ivan-klass, can you identify the portion of your `pyproject.toml` file that is causing the problem? If so, please provide a minimal repro case. Are you sure that it's using valid `toml` syntax that conforms to the latest `toml` standard?

**Comment by yli-leah** [comment]
@erictraut I have the same issue.  Even if I just kept my pyproject.toml as simple as
```
[project]
name = "c"
```

I am still getting 
```
Pyproject file parse attempt 1 error: {}
Pyproject file parse attempt 2 error: {}
Pyproject file parse attempt 3 error: {}
Pyproject file parse attempt 4 error: {}
Pyproject file parse attempt 5 error: {}
Pyproject file parse attempt 6 error: {}
```

**Comment by erictraut** [comment]
@yli-leah, one pyright user found that this problem was due to an out-of-date version of node installed on their system. You could try to install a recent version of node to see if that fixes the problem for you.
